# Эта программа позволит после ввода числа n для каждого из чисел
# от 0 до n (включительно) вывести фразу:
# "Квадрат числа [число] равен [число]" (без кавычек)

# Содаём переменную для управления циклом
keep_go = 'д'
while keep_go == 'д':
    n = int(input())         #  Вводим натуральное число
    for i in range(n + 1):   #  Организуем цикл
        print('Квадрат числа', i, 'равен', (i  ** 2))  # Выводим на экран фразу
       
        
# Убедиться, что пользователь хочет ещё ввести число.
    keep_go = input('Хотите ещё ввести число? ' +
                    'Введите д, если да: ')
